name: Build releases

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build ${{matrix.target}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install musl-tools

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: llvm-tools-preview
          target: ${{matrix.target}}

      - name: Install cbindgen
        run: cargo install cbindgen

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{matrix.target}}

      - name: Build dynamic library
        run: make TARGET=${{matrix.target}} build-cross

      - name: Run C tests
        # We need to store the exit code since cross-util will always exit with 0
        run: |
          EXIT_CODE=$(cross-util run --target ${{matrix.target}} -- 'make TARGET=${{matrix.target}} test-c; echo $?' | tail -1)
          exit "$EXIT_CODE"

      - name: Run C++ tests
        # We need to store the exit code since cross-util will always exit with 0
        run: |
          EXIT_CODE=$(cross-util run --target ${{matrix.target}} -- 'make TARGET=${{matrix.target}} test-cpp; echo $?' | tail -1)
          exit "$EXIT_CODE"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Add built files to archive
        uses: actions/upload-artifact@v3
        with:
          name: c2pa-c_${{matrix.target}}-${{ steps.sha.outputs.sha_short }}.zip
          path: |
            README.md
            include/**
            examples/**
          retention-days: 3

      - name: Add supporting files to archive
        uses: actions/upload-artifact@v3
        with:
          name: c2pa-c_${{matrix.target}}-${{ steps.sha.outputs.sha_short }}.zip
          path: target/${{matrix.target}}/release/libc2pa_c*
          retention-days: 3
