name: Build releases

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-linux-aarch64:
    name: Build aarch64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install musl-tools

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: llvm-tools-preview
          targets: aarch64-unknown-linux-musl

      - name: Install cbindgen
        run: cargo install cbindgen

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: aarch64-unknown-linux-musl

      - name: Build dynamic library
        run: RUSTFLAGS="-Ctarget-feature=-crt-static" cross build --release --target aarch64-unknown-linux-musl

      - name: Add built files to archive
        uses: actions/upload-artifact@v3
        with:
          name: c2pa-c_aarch64-unknown-linux-musl-${{ steps.sha.outputs.sha_short }}.zip
          path: |
            README.md
            include/**
            examples/**
          retention-days: 3

      - name: Add supporting files to archive
        uses: actions/upload-artifact@v3
        with:
          name: c2pa-c_aarch64-unknown-linux-musl-${{ steps.sha.outputs.sha_short }}.zip
          path: target/aarch64-unknown-linux-musl/release/libc2pa_c*
          retention-days: 3

  build-linux-x86_64:
    name: Build x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install musl-tools

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: llvm-tools-preview
          targets: x86_64-unknown-linux-musl

      - name: Install cbindgen
        run: cargo install cbindgen

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: x86_64-unknown-linux-musl

      - name: Build dynamic library
        run: RUSTFLAGS="-Ctarget-feature=-crt-static" cargo build --release --target x86_64-unknown-linux-musl

      - name: Add built files to archive
        uses: actions/upload-artifact@v3
        with:
          name: c2pa-c_x86_64-unknown-linux-musl-${{ steps.sha.outputs.sha_short }}.zip
          path: |
            README.md
            include/**
            examples/**
          retention-days: 3

      - name: Add supporting files to archive
        uses: actions/upload-artifact@v3
        with:
          name: c2pa-c_x86_64-unknown-linux-musl-${{ steps.sha.outputs.sha_short }}.zip
          path: target/x86_64-unknown-linux-musl/release/libc2pa_c*
          retention-days: 3
